apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: v1
  annotations:
    iter8.tools/ready: "true"
    iter8.tools/track: current
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/version: v1
    spec:
      containers:
      - name: backend
        image: BACKEND_TAG
        env:
        - name: VERSION
          value: v1
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-current
spec:
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: v1
  ports:
  - port: 8091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: v2
  annotations:
    iter8.tools/ready: "true"
    iter8.tools/track: candidate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/version: v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/version: v2
    spec:
      containers:
      - name: backend
        image: BACKEND_TAG
        env:
        - name: VERSION
          value: v2
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-candidate
spec:
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: v2
  ports:
  - port: 8091
