# Get Iter8
FROM golang:1.18-buster as builder

WORKDIR /

COPY backend/ backend/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o be backend/main.go

### Multi-stage Docker build
### New image below

# Small linux image with iter8 binary
FROM debian:buster-slim
WORKDIR /
COPY --from=builder /be /backend

ENTRYPOINT ["/backend"]
