name: test iter8 gh-action

on:
  workflow_dispatch:

jobs:
  gh-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: run httpbin
      run: |
        set -e
        docker pull kennethreitz/httpbin
        docker run -p 80:80 kennethreitz/httpbin &
        HOST_IP=$(ip -f inet addr show docker0 | grep -Po 'inet \K[\d.]+')
        echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://$HOST_IP/get)" != "200" ]]; do
          sleep 5; 
        done;

    - name: install Iter8 CLI
      uses: ./
    - name: version
      run: | 
        iter8 version
    - name: launch
      run: |
        iter8 launch --localChart -c testdata/charts/iter8 \
        --set "tasks={http}" \
        --set http.url="http://$HOST_IP/get"
    - name: assert
      run: |
        iter8 assert -c completed -c nofailure


  kubernetes-http-experiment:
    name: Kubernetes http load test    
    runs-on: ubuntu-latest
    steps:
    - uses: iter8-tools/iter8@v0.12-pre
    - name: Start kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        wait: 300s
    - name: create app
      run: |
        kubectl create deployment httpbin --image=kennethreitz/httpbin
        kubectl expose deployment httpbin --type=ClusterIP --port=80
        kubectl wait --for=condition=available --timeout=60s deploy/httpbin
    - name: iter8 k launch
      run: |
        iter8 k launch \
        --set tasks={http} \
        --set http.url="http://httpbin.default/get" \
        --set runner=job
    - name: try other iter8 k commands
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete

