name: Test experiment charts using local charts

on:
  workflow_dispatch:

# Kind versions used to test Iter8 on different versions of Kubernetes
# From: https://github.com/kubernetes-sigs/kind/releases

jobs:

  http-experiment:
    name: HTTP load test
    runs-on: ubuntu-latest

    steps:    
    - name: Check out code
      uses: actions/checkout@v3

    - name: go
      run: |
        go version
        which go

    - name: Install Iter8
      run: |
        GOBIN=/usr/local/bin go install github.com/iter8-tools/iter8@v0.14
        which iter8

    - name: Start kind cluster ${{ matrix.version }}
      uses: helm/kind-action@v1.5.0
      with:
        wait: 300s

    - name: Create app
      run: |
        kubectl create deployment httpbin --image=kennethreitz/httpbin
        kubectl expose deployment httpbin --type=ClusterIP --port=80
        kubectl wait --for=condition=available --timeout=60s deploy/httpbin

    - name: iter8 k launch
      run: |
        iter8 k launch \
        --localChart \
        --chartName charts/iter8 \
        --set tasks={http} \
        --set http.url="http://httpbin.default/get" \
        --set runner=job

    - name: Try other iter8 k commands
      run: |
        iter8 k assert -c completed -c nofailure --timeout 60s
        iter8 k report
        iter8 k log
        iter8 k delete
      
