name: Publish A/B/n Sample Docker images

on:
  workflow_dispactch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: rojopolis/spellcheck-github-actions@0.29.0
      with:
        source_files: ../../*.md ../../docs/**/*.md
